# -*- coding: utf-8 -*-
"""Análisis_Ventas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSooKSVOE0FVj8LyaVBUGVm6whQS4x-k

# Analisis de ventas DSMarket
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

# Cargar el DataFrame desde el archivo preprocesado
df = pd.read_csv('/content/drive/MyDrive/Proyecto DSMarket/DSMarket/DatosAgrupadosEnSemanas.csv.gz')

df['date'] = pd.to_datetime(df['año'].astype(str) + df['semana'].astype(str).str.zfill(2) + '1', format='%G%V%u')

df_phi = df[df['region']=='Philadelphia']
df_bos = df[df['region']=='Boston']
df_ny = df[df['region']=='New York']

"""## Gráfico de Ventas"""

df_sell = df[df['ventas'] > 0]

plt.figure(figsize=(12, 6))
plt.plot(df_sell['date'], df_sell['ventas'])
plt.xlabel('Fecha')
plt.ylabel('Ventas')
plt.title('Ventas DSMarket')
plt.grid(True)
plt.show()

"""##Ventas"""

ventas_tot=df['ventas'].sum()
print(f'Ventas Totales: {ventas_tot:,.2f}')

"""###CIUDAD"""

def ventas_totales_por_region(df):
  """Calcula las ventas totales por región, mostrando resultados legibles."""

  ventas_region = df.groupby('region')['ventas'].sum().reset_index()

  for _, row in ventas_region.iterrows():
    region = row['region']
    ventas = row['ventas']
    print(f"Región: {region}, Ventas totales: {ventas:,.2f}")


# Calcular y mostrar las ventas totales por región para todo el DataFrame
print("Ventas totales por región:")
ventas_totales_por_region(df)

"""###TIENDA

####Philadelphia
"""

for i in [df_phi[df_phi['store']=='Midtown_Village'],df_phi[df_phi['store']=='Yorktown'],df_phi[df_phi['store']=='Queen_Village']]:
  print(i['store'].unique(),)
  ventas_totales_por_region(i)
  print('--'*20)

"""####New York"""

for i in [df_ny[df_ny['store']=='Greenwich_Village'],
          df_ny[df_ny['store']=='Harlem'],
          df_ny[df_ny['store']=='Tribeca'],
          df_ny[df_ny['store']=='Brooklyn']]:
  print(i['store'].unique(),)
  ventas_totales_por_region(i)
  print('--'*20)

"""####Boston"""

for i in [df_bos[df_bos['store']=='South_End'],
          df_bos[df_bos['store']=='Roxbury'],
          df_bos[df_bos['store']=='Back_Bay']]:
  print(i['store'].unique(),)
  ventas_totales_por_region(i)
  print('--'*20)

"""##Crecimiento medio de ventas ANUAL

No se han tenido en cuenta los registros de 2016 ya que no está el año entero y este puede afectar a los porcentajes de crecimineto
"""

df_2016 = df[df['año'] < 2016]

def crecimiento(df):
   df_2016 = df[df['año'] < 2016]
   # Agrupar las ventas totales por año
   ventas_por_año = df_2016.groupby('año')['ventas'].sum().reset_index()

   # Calcular el crecimiento de ventas año a año
   ventas_por_año['ventas_anterior'] = ventas_por_año['ventas'].shift(1)

   # Calcular el porcentaje de crecimiento
   ventas_por_año['crecimiento_porcentaje'] = ((ventas_por_año['ventas'] - ventas_por_año['ventas_anterior']) / ventas_por_año['ventas_anterior']) * 100

   # Ver los resultados
   print(ventas_por_año[['año', 'ventas', 'crecimiento_porcentaje']])

   # Calcular el crecimiento medio (ignorando valores NaN)
   crecimiento_medio = ventas_por_año['crecimiento_porcentaje'].mean()

   # Mostrar el crecimiento medio
   print(f"Crecimiento medio de ventas anual: {crecimiento_medio:.2f}%")

crecimiento(df_2016)

"""###CIUDAD"""

for i in [df_phi,df_bos,df_ny]:
  print(i['region'].unique())
  crecimiento(i)

"""###TIENDA

####Philadelphia
"""

df_phi['store'].unique()

for i in [df_phi[df_phi['store']=='Midtown_Village'],df_phi[df_phi['store']=='Yorktown'],df_phi[df_phi['store']=='Queen_Village']]:
  print(i['store'].unique(),)
  crecimiento(i)
  print('--'*20)

"""####New York"""

df_ny['store'].unique()

for i in [df_ny[df_ny['store']=='Greenwich_Village'],
          df_ny[df_ny['store']=='Harlem'],
          df_ny[df_ny['store']=='Tribeca'],
          df_ny[df_ny['store']=='Brooklyn']]:
  print(i['store'].unique(),)
  crecimiento(i)
  print('--'*20)

"""####Boston"""

df_bos['store'].unique()

for i in [df_bos[df_bos['store']=='South_End'],
          df_bos[df_bos['store']=='Roxbury'],
          df_bos[df_bos['store']=='Back_Bay']]:
  print(i['store'].unique(),)
  crecimiento(i)
  print('--'*20)

"""##Facturacion"""

df['revenue']=df['ventas']*df['sell_price']

revenue_tot=df['revenue'].sum()
print(f'Facturacion Total: {revenue_tot:,.2f}$')

"""###CIUDAD"""

def revenue_by_region(df):
  """Calcula el revenue total por región, mostrando resultados legibles."""

  revenue_region = df.groupby('region')['revenue'].sum().reset_index()

  for _, row in revenue_region.iterrows():
    region = row['region']
    revenue = row['revenue']
    print(f"Región: {region}, Revenue: {revenue:,.2f}$")


# Calcular y mostrar el revenue total por región para todo el DataFrame
print("Revenue total por región:")
revenue_by_region(df)

"""###TIENDA"""

def revenue_by_city_store(df):
  """Calcula el revenue por ciudad y tienda, mostrando resultados legibles."""

  revenue_city_store = df.groupby(['region', 'store'])['revenue'].sum().reset_index()

  for _, row in revenue_city_store.iterrows():
    city = row['region']
    store = row['store']
    revenue = row['revenue']
    print(f"Ciudad: {city}, Tienda: {store}, Revenue: {revenue:,.2f}$")

# Calcular y mostrar el revenue por ciudad y tienda para todo el DataFrame
print("Revenue por ciudad y tienda:")
revenue_by_city_store(df)

"""#ANALISIS DE VENTAS DE ITEMS

##Items mas vendidos

###CIUDAD
"""

def top_selling_items_by_region(df):
  """Muestra los artículos más vendidos en cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    top_items = df_region.groupby('item')['ventas'].sum().sort_values(ascending=False).head(5)
    print(f"\nRegión: {region}")
    print("Artículos más vendidos:")
    print(top_items)


# Mostrar los artículos más vendidos en cada región
top_selling_items_by_region(df)

"""###TIENDA"""

def top_selling_items_by_store_region(df):
  """Muestra los artículos más vendidos en cada tienda de cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    print(f"\nRegión: {region}")
    for store in df_region['store'].unique():
      df_store = df_region[df_region['store'] == store]
      top_items = df_store.groupby('item')['ventas'].sum().sort_values(ascending=False).head(5)
      print(f"\nTienda: {store}")
      print("Artículos más vendidos:")
      print(top_items)


# Mostrar los artículos más vendidos en cada tienda de cada región
top_selling_items_by_store_region(df)

"""##Items que mas facturan

###TIENDA
"""

def top_revenue_items_by_store_region(df):
  """Muestra los artículos con más revenue en cada tienda de cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    print(f"\nRegión: {region}")
    for store in df_region['store'].unique():
      df_store = df_region[df_region['store'] == store]
      top_revenue_items = df_store.groupby('item')['revenue'].sum().sort_values(ascending=False).head(5)
      print(f"\nTienda: {store}")
      print("Artículos con más revenue:")
      print(top_revenue_items)


# Mostrar los artículos con más revenue en cada tienda de cada región
top_revenue_items_by_store_region(df)

"""##Items menos vendidos

###CIUDAD
"""

def bottom_selling_items_by_region(df):
  """Muestra los artículos que menos se venden en cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    bottom_items = df_region.groupby('item')['ventas'].sum().sort_values(ascending=True).head(5)
    print(f"\nRegión: {region}")
    print("Artículos que menos se venden:")
    print(bottom_items)


# Mostrar los artículos que menos se venden en cada región
bottom_selling_items_by_region(df)

"""###TIENDA"""

def bottom_selling_items_by_store_region(df):
  """Muestra los artículos que menos se venden en cada tienda de cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    print(f"\nRegión: {region}")
    for store in df_region['store'].unique():
      df_store = df_region[df_region['store'] == store]
      bottom_items = df_store.groupby('item')['ventas'].sum().sort_values(ascending=True).head(5)
      print(f"\nTienda: {store}")
      print("Artículos que menos se venden:")
      print(bottom_items)


# Mostrar los artículos que menos se venden en cada tienda de cada región
bottom_selling_items_by_store_region(df)

"""##Items que menos facturan

###TIENDA
"""

def bottom_revenue_items_by_store_region(df):
  """Muestra los artículos con menos revenue en cada tienda de cada región."""

  for region in df['region'].unique():
    df_region = df[df['region'] == region]
    print(f"\nRegión: {region}")
    for store in df_region['store'].unique():
      df_store = df_region[df_region['store'] == store]
      bottom_revenue_items = df_store.groupby('item')['revenue'].sum().sort_values(ascending=True).head(5)
      print(f"\nTienda: {store}")
      print("Artículos con menos revenue:")
      print(bottom_revenue_items)


# Mostrar los artículos con menos revenue en cada tienda de cada región
bottom_revenue_items_by_store_region(df)