# -*- coding: utf-8 -*-
"""Cluster_Tiendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQoi6UhDdl1fSeddCXQ7JElc4jzPB5pF

#**Task 2: Clustering**
##DSMarket ALAN V1

#**Clustering de Tiendas**

#Librerias y ficheros
"""

# Commented out IPython magic to ensure Python compatibility.
# silence warnings
import warnings
warnings.filterwarnings("ignore")

# operating system
import os

# time calculation to track some processes
import time

# numeric and matrix operations
import numpy as np
import pandas as pd

# loading ploting libraries
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# python core library for machine learning and data science
import sklearn
from sklearn import set_config
set_config(transform_output = "pandas")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from google.colab import drive
drive.mount('/content/drive')

#CWD = os.getcwd()
#PATH_DATA = os.path.join(CWD, "data")

"""#Importamos fichero"""

df = pd.read_csv("/content/drive/MyDrive/DSMarket/DatosAgrupadosEnSemanas.csv.gz")
df.head()

store_unique = df['store_code'].nunique()
print(f"Tenemos un total de {store_unique} tiendas únicas en el dataset.")

"""---

#Feature Engineering

**Temporales**
"""

df['date'] = pd.to_datetime(df['yearweek'].astype(str) + '0', format='%Y%W%w')
df['month'] = df['date'].dt.month

df['quarter'] = df['date'].dt.to_period('Q')

df['is_event'] = np.where(df['event'] == 'Sin_Evento', 0, 1)

df['date'].min()

df['date'].max()

"""Filtramos datos para solo utilizar 2011 hasta 2015."""

# Filter data to include only the selected years (2011 to 2015)
df_filtered = df[(df['date'].dt.year >= 2011) & (df['date'].dt.year <= 2015)].copy()

total_sales_all_stores = df_filtered['ventas'].sum()
print(f"Total sales of all stores combined: {total_sales_all_stores}")

"""## **Venta**

**Proporción de Ventas de la Tienda respecto a Ventas Totales**

Fórmula: Proporción de Ventas = Ventas de la Tienda / Ventas Totales

Interpretación: Mide la participación de cada tienda en las ventas totales. Esto puede ayudarte a identificar qué tiendas contribuyen más o menos a las ventas generales.
"""

df_store_sales = df_filtered.groupby('store_code')['ventas'].sum().reset_index()
df_store_sales.rename(columns={'ventas': 'total_ventas_store'}, inplace=True)
df_store_sales['total_ventas'] = df_filtered['ventas'].sum()
df_store_sales['store_sales_ratio'] = df_store_sales['total_ventas_store'] / df_store_sales['total_ventas']
df_store_sales

"""**Ventas Promedio por Categoría o Departamento**

Fórmula: Ventas Promedio por Categoría = Ventas de la Categoría en la Tienda / Número de Categorías en la Tienda

Interpretación: Indica la eficiencia de ventas de diferentes categorías dentro de cada tienda. Puede ser útil para comparar tiendas que venden diferentes productos.
"""

df_avg_sales_category = df_filtered.groupby(['store_code', 'category'])['ventas'].mean().reset_index()
df_avg_sales_category.columns = ['store_code', 'category', 'avg_sales_per_category']
df_avg_sales_category = df_avg_sales_category.pivot(index='store_code', columns='category', values='avg_sales_per_category')
df_avg_sales_category.columns = ['avg_sales_cat_' + col for col in df_avg_sales_category.columns]
df_avg_sales_category.reset_index(inplace=True)
df_avg_sales_category

"""**Ratio de Ventas por Semana o Trimestre**

Fórmula: Ratio de Ventas por Semana = Ventas de la Tienda en la Semana / Número de Semanas

Interpretación: Muestra el promedio de ventas semanal, ayudando a entender el comportamiento estacional o la estabilidad de las ventas a lo largo del tiempo.
"""

df_sales_quarter = df_filtered.groupby(['store_code', 'trimestre'])['ventas'].sum().reset_index()
df_sales_quarter = df_sales_quarter.pivot(index='store_code', columns='trimestre', values='ventas')
df_sales_quarter.columns = ['ventas_T1', 'ventas_T2', 'ventas_T3', 'ventas_T4']
df_sales_quarter.reset_index(inplace=True)
df_sales_quarter

"""**Ratio de Eventos a Ventas**

Fórmula: Ratio de Eventos a Ventas = Número de Eventos en la Tienda / Ventas Totales de la Tienda

Interpretación: Este ratio puede indicar cómo los eventos (promociones, descuentos, etc.) impactan en las ventas totales de la tienda.

**Ratio de Ventas en Días de Evento**

Fórmula: Ratio de Ventas en Días de Evento = Ventas durante Eventos / Ventas Totales

Interpretación: Mide el impacto de los días de eventos en las ventas totales. Puede mostrar si las ventas de una tienda dependen en gran medida de eventos promocionales.**
"""

df_store_event_sales = df_filtered.groupby(['store_code', 'is_event'])['ventas'].sum().reset_index()

df_store_event_sales = df_store_event_sales.pivot(index='store_code', columns='is_event', values='ventas')
df_store_event_sales.columns = ['event_sales', 'no_event_sales']

df_store_event_sales['total_store_sales'] = df_filtered.groupby('store_code')['ventas'].sum()
df_store_event_sales['count_events'] = df_filtered.groupby('store_code')['is_event'].sum()

df_store_event_sales['ratio_eventos_ventas'] = df_store_event_sales['count_events'] / df_store_event_sales['total_store_sales']

df_store_event_sales['ratio_ventas_en_eventos'] = df_store_event_sales['event_sales'] / df_store_event_sales['total_store_sales']

df_store_event_sales.drop(columns=['event_sales','no_event_sales','total_store_sales','count_events'], inplace=True)

df_store_event_sales.reset_index(inplace=True)

df_store_event_sales

"""**Ratio de Ventas por Región**

Fórmula: Ratio de Ventas por Región = Ventas de la Tienda / Ventas Totales en la Región

Interpretación: Ayuda a entender cómo cada tienda se desempeña en relación con otras tiendas en la misma región.
"""

df_region_sales = df_filtered.groupby('region')['ventas'].sum().reset_index()
df_region_sales

df_store_sales

"""**Ratio de Crecimiento de Ventas Anual**"""

# Fórmula para sacar Ratio de Crecimiento de Ventas Anual = (Ventas Año Actual - Ventas Año Anterior) / Ventas Año Anterior

df_annual_sales = df_filtered.groupby(['store_code', df_filtered['date'].dt.year])['ventas'].sum().reset_index()

df_annual_sales.rename(columns={'ventas': 'annual_sales', 'date': 'year'}, inplace=True)

df_annual_sales_pivot = df_annual_sales.pivot(index='store_code', columns='year', values='annual_sales')

df_annual_sales_pivot['growth_rate'] = (df_annual_sales_pivot[df_annual_sales_pivot.columns[-1]] - df_annual_sales_pivot[df_annual_sales_pivot.columns[-2]]) / df_annual_sales_pivot[df_annual_sales_pivot.columns[-2]]

df_annual_sales_pivot.reset_index(inplace=True)

df_annual_sales_pivot.columns = ['store_code', 'ventas_2011', 'ventas_2012', 'ventas_2013', 'ventas_2014', 'ventas_2015', 'growth_rate']
df_annual_sales_pivot

"""**Precio de Venta Promedio Ajustado por Categoría**

Interpretación: Normaliza el precio de venta promedio considerando el número de categorías o departamentos, para comparar mejor tiendas con diferentes mix de productos.

Fórmula: Precio de Venta Promedio Ajustado = Precio de Venta Promedio / Número de Categorías o Departamentos
"""

df_avg_price_category = df_filtered.groupby(['store_code', 'category'])['sell_price'].mean().reset_index()
df_avg_price_category.columns = ['store_code', 'category', 'avg_price_per_category']

df_category_count = df_filtered.groupby('store_code')['category'].nunique().reset_index()
df_category_count.rename(columns={'category': 'category_count'}, inplace=True)

df_avg_price_category = pd.merge(df_avg_price_category, df_category_count, on='store_code')

df_avg_price_category['adjusted_avg_price'] = df_avg_price_category['avg_price_per_category'] / df_avg_price_category['category_count']

df_avg_price_category_pivot = df_avg_price_category.pivot(index='store_code', columns='category', values='adjusted_avg_price')
df_avg_price_category_pivot.columns = ['adj_avg_price_cat_' + col for col in df_avg_price_category_pivot.columns]
df_avg_price_category_pivot.reset_index(inplace=True)

df_avg_price_category_pivot

"""# Clustering

## Merged df: df_features
"""

df_features = df_store_sales \
    .merge(df_avg_sales_category, on='store_code', how='left') \
    .merge(df_sales_quarter, on='store_code', how='left') \
    .merge(df_store_event_sales, on='store_code', how='left') \
    .merge(df_annual_sales_pivot, on='store_code', how='left') \
    .merge(df_avg_price_category_pivot, on='store_code', how='left')

df_features.set_index('store_code', inplace=True)

df_features

df_features.isnull().sum()

df_features.columns

df_features = df_features[[
    #'total_ventas_store',
    #'total_ventas',
    'store_sales_ratio',
    'avg_sales_cat_ACCESORIES',
    'avg_sales_cat_HOME_&_GARDEN',
    'avg_sales_cat_SUPERMARKET',
    'ventas_T1',
    'ventas_T2',
    'ventas_T3',
    'ventas_T4',
    #'ratio_eventos_ventas',
    'ratio_ventas_en_eventos',
    'ventas_2011',
    'ventas_2012',
    'ventas_2013',
    'ventas_2014',
    'ventas_2015',
    'growth_rate',
    #'adj_avg_price_cat_ACCESORIES',
    #'adj_avg_price_cat_HOME_&_GARDEN',
    #'adj_avg_price_cat_SUPERMARKET'
    ]]

"""---

## Evaluate Features

## Feature Variance
**Interpret the Results:** If you find features with near-zero variance, consider removing them as they are unlikely to help in differentiating clusters
"""

feature_variances = df_features.var()

print("Feature Variances:\n", feature_variances)

"""## Feature Correlation
**Interpret the Results: **Look for pairs of features with a high absolute correlation value (close to +1 or -1). If two features are highly correlated, consider removing one or combining them (e.g., creating a new feature that represents the average or sum of the two).
"""

correlation_matrix = df_features.corr()

print("Feature Correlation Matrix:\n", correlation_matrix)

"""---

## Estandarizacion de datos
"""

from sklearn.preprocessing import StandardScaler

selected_features = df_features

selected_features = selected_features.fillna(0)  # or use another method to handle NaNs

scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""##  PCA"""

from sklearn.decomposition import PCA

n_components=3

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

plt.figure(figsize=(8, 5))
plt.bar(range(1, n_components + 1), explained_variance, alpha=0.7, align='center', label='Varianza explicada por componente')
plt.step(range(1, n_components + 1), cumulative_variance, where='mid', label='Varianza acumulada')
plt.xlabel('Componentes principales')
plt.ylabel('Varianza explicada')
plt.title('Varianza explicada por cada componente principal')
plt.legend(loc='best')
plt.show()

"""##KMeans"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

n_clusters = 3

kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(A)

labels = kmeans.labels_

plt.figure(figsize=(8, 5))
plt.scatter(A['pca0'], A['pca1'], c=labels, cmap='viridis', marker='o', edgecolor='k', s=100)
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.title('Clusters obtenidos con KMeans usando PCA')
plt.colorbar(label='Cluster')
plt.show()

inertia = kmeans.inertia_
print(f"Inercia del modelo KMeans con {n_clusters} clusters: {inertia}")

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

range_n_clusters = range(1, 11)

for n_clusters in range_n_clusters:
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(A)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range_n_clusters, inertia, marker='o', linestyle='-')
plt.xlabel('Número de Clusters')
plt.ylabel('Inercia')
plt.title('Método del Codo para Determinar el Número Óptimo de Clusters')
plt.grid(True)
plt.show()

"""## Coeficiente de Silueta"""

from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(A, labels)
print(f"Coeficiente de Silueta promedio: {silhouette_avg}")

"""## Asignacion de labels"""

df_features['cluster_3'] = labels

df_features

"""## Ficha Clusters Productos"""

features_df = df_features[[
    #'total_ventas_store',
    #'total_ventas',
    'store_sales_ratio',
    'avg_sales_cat_ACCESORIES',
    'avg_sales_cat_HOME_&_GARDEN',
    'avg_sales_cat_SUPERMARKET',
    'ventas_T1',
    'ventas_T2',
    'ventas_T3',
    'ventas_T4',
    #'ratio_eventos_ventas',
    'ratio_ventas_en_eventos',
    'ventas_2011',
    'ventas_2012',
    'ventas_2013',
    'ventas_2014',
    'ventas_2015',
    'growth_rate',
    #'adj_avg_price_cat_ACCESORIES',
    #'adj_avg_price_cat_HOME_&_GARDEN',
    #'adj_avg_price_cat_SUPERMARKET'
    'cluster_3'
    ]].groupby("cluster_3").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

"""

---

"""