# -*- coding: utf-8 -*-
"""Cluster_Productos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEqSYoSNIdNkRRMSL3w6h8KDdt0LfTiw

#**Task 2: Clustering**

#**Clustering de Productos**
### **Objetivo**
*   Agrupar 3049 ítems en distintos grupos basados en su comportamiento de ventas con el fin de evaluar el performance de diferentes campañas de marketing.
*   ¿Cuántos grupos consideramos?

#Librerias y ficheros
"""

# Commented out IPython magic to ensure Python compatibility.
# silence warnings
import warnings
warnings.filterwarnings("ignore")

# operating system
import os

# time calculation to track some processes
import time

# numeric and matrix operations
import numpy as np
import pandas as pd

# loading ploting libraries
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# python core library for machine learning and data science
import sklearn
from sklearn import set_config
set_config(transform_output = "pandas")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from google.colab import drive
drive.mount('/content/drive')

#CWD = os.getcwd()
#PATH_DATA = os.path.join(CWD, "data")

"""#Importamos fichero"""

df = pd.read_csv("/content/drive/MyDrive/DSMarket/DatosAgrupadosEnSemanas.csv.gz")
df.head()

item_unique = df['item'].nunique()
print(f"Tenemos un total de {item_unique} items únicos en el dataset.")

"""---

#Feature Engineering

##Variables relacionadas a tiempo
Creacion de variables relacionadas a fechas con la finalidad de facilitar el análisis de datos a nivel trimestral, como ventas, ingresos, o cualquier otra métrica temporal.
"""

#Convertimos la columna yearweek (año y semana del año) en un formato de fecha completa.
df['date'] = pd.to_datetime(df['yearweek'].astype(str) + '0', format='%Y%W%w')

#Extraemos el número de mes de la columna date recién creada.
df['month'] = df['date'].dt.month

#Extraemos el trimestre del año al que pertenece cada fecha.
df['quarter'] = df['date'].dt.to_period('Q')

#Creamos una variable binaria para indicar si hubo un evento o no en una semana determinada.
df['is_event'] = np.where(df['event'] == 'Sin_Evento', 0, 1)

"""### Selección de períodos a analizar
Nuestro dataset cuenta con información desde 2011-01-30 hasta 2016-04-24. Es decir, faltan datos del primer mes del 2011 y de gran parte de 2016.
"""

df['date'].min()

df['date'].max()

"""Filtramos datos para solo utilizar 2011 hasta 2015 dado que la ausencia de datos en el año 2016 podría afectar negativamente la calidad del modelo del clustering generando una inconsistencia temporal, sesgando los resultados."""

df_filtered = df[(df['date'].dt.year >= 2011) & (df['date'].dt.year <= 2015)].copy()

"""##Variables relacionadas a ventas

### Ventas totales por item
Periodo 2011-2015.
"""

df_total_sales = df_filtered.groupby('item')['ventas'].sum().reset_index()
df_total_sales.columns = ['item', 'total_sales']
df_total_sales

"""###Ventas totales por región para cada ítem"""

df_ventas_region = df_filtered.groupby(['item', 'region'])['ventas'].sum().reset_index()
df_ventas_region = df_ventas_region.pivot(index='item', columns='region', values='ventas')
df_ventas_region.columns = ['ventas_Boston', 'ventas_New York', 'ventas_Philadelphia']
df_ventas_region.reset_index(inplace=True)
df_ventas_region

"""### Ratio de ventas regionales para cada ítem"""

# Combina las características de ventas regionales calculando la proporción de ventas en cada región respecto a las ventas totales.
ratio_ventas_Boston = df_ventas_region['ventas_Boston'] / df_total_sales['total_sales']
df_total_sales['ratio_ventas_Boston'] = ratio_ventas_Boston

ratio_ventas_Nueva_York = df_ventas_region['ventas_New York'] / df_total_sales['total_sales']
df_total_sales['ratio_ventas_Nueva_York'] = ratio_ventas_Nueva_York

ratio_ventas_Filadelfia = df_ventas_region['ventas_Philadelphia'] / df_total_sales['total_sales']
df_total_sales['ratio_ventas_Filadelfia'] = ratio_ventas_Filadelfia

df_total_sales

"""### Ratio de las ventas para cada ítem por trimestre respecto a las ventas totales"""

#Agrupamos las ventas por cada ítem y trimestre para sumar las ventas de cada ítem en cada trimestre.
df_sales_quarter = df_filtered.groupby(['item', 'trimestre'])['ventas'].sum().reset_index()

#Usamos pivot para reorganizar los datos de tal manera que cada ítem tenga sus ventas distribuidas en columnas por trimestre.
df_sales_quarter = df_sales_quarter.pivot(index='item', columns='trimestre', values='ventas')
df_sales_quarter.columns = ['ventas_T1', 'ventas_T2', 'ventas_T3', 'ventas_T4']

# Creamos una nueva columna que sume las ventas de todos los trimestres para obtener las ventas totales de cada ítem.
df_sales_quarter['total_sales'] = df_sales_quarter[['ventas_T1', 'ventas_T2', 'ventas_T3', 'ventas_T4']].sum(axis=1)

#Para cada trimestre, se calcula el porcentaje de las ventas totales que ocurrió en ese trimestre.
df_sales_quarter['ventas_T1_ratio'] = df_sales_quarter['ventas_T1'] / df_sales_quarter['total_sales']
df_sales_quarter['ventas_T2_ratio'] = df_sales_quarter['ventas_T2'] / df_sales_quarter['total_sales']
df_sales_quarter['ventas_T3_ratio'] = df_sales_quarter['ventas_T3'] / df_sales_quarter['total_sales']
df_sales_quarter['ventas_T4_ratio'] = df_sales_quarter['ventas_T4'] / df_sales_quarter['total_sales']

#Rellenamos los valores faltantes (NaN) con ceros, en caso de que un ítem no haya tenido ventas en uno o más trimestres.
df_sales_quarter.fillna(0, inplace=True)

#Restablecemos el índice.
df_sales_quarter.reset_index(inplace=True)
df_sales_quarter.drop(columns=['total_sales', 'ventas_T1', 'ventas_T2', 'ventas_T3', 'ventas_T4'], inplace=True)
df_sales_quarter

"""### Volatilidad de Ventas por Ítem

Capturar cómo de "estables" o "inestables" son las ventas de un producto. Los ítems con alta volatilidad podrían tener ventas más erráticas, lo que puede deberse a factores externos como promociones o eventos.
"""

df_sales_volatility = df_filtered.groupby('item')['ventas'].std().reset_index()
df_sales_volatility.columns = ['item', 'sales_volatility']
df_sales_volatility

"""##Variables relacionadas a precio

### Precio Promedio por Ítem

El precio promedio es un indicador clave que nos permitirá identificar qué productos tienden a ser más baratos o caros, y cómo podría relacionarse su precio con las ventas.
"""

df_avg_price = df_filtered.groupby('item')['sell_price'].mean().reset_index()
df_avg_price.columns = ['item', 'avg_price']
df_avg_price

"""### Característica de Precio Relativo

Creamos una nueva característica llamada "precio relativo" mediante la comparacion del precio promedio de cada artículo con el precio promedio de todos los artículos dentro de la misma categoría o región.


Normaliza el precio de cada artículo comparándolo con el precio promedio de los artículos de su misma categoría. Esto ayuda a entender cómo se posiciona el precio de un artículo en relación con otros similares.

Nota: Para crear la característica de "precio relativo", necesitas tener una columna de "categoría" o "región" en tus datos que agrupe los artículos en diferentes categorías. Si no tienes esta columna, considera usar las columnas existentes que tengan sentido en tu contexto.
"""

#Calculamos el precio promedio de cada categoría y asigna ese valor a cada ítem dentro de la categoría correspondiente.
precio_promedio_categoria = df_filtered.groupby('category')['sell_price'].transform('mean')

# Creamos una nueva característica de precio relativo.
df_avg_price['precio_relativo'] = df_avg_price['avg_price'] / precio_promedio_categoria

df_avg_price

"""### Sensibilidad al precio por Ítem

Crucial para entender cómo los cambios en el precio afectan las ventas de un ítem. Productos con alta sensibilidad podrían requerir estrategias de precios más ajustadas para maximizar sus ventas.
"""

df_price_sensitivity = df_filtered.groupby('item').apply(lambda x: x['sell_price'].corr(x['ventas'])).reset_index()
df_price_sensitivity.columns = ['item', 'price_sensitivity']
df_price_sensitivity.fillna(0, inplace=True)
df_price_sensitivity

"""### Volatilidad Estacional de Precios

Agrupamos el DataFrame por la columna category y se calcula la media de los precios de venta (sell_price). Luego, el método transform('mean') asegura que este valor promedio se asigne a cada ítem dentro de su categoría.

Seguidamente, tomamos el precio promedio del ítem (avg_price) y se divide entre el precio promedio de la categoría a la que pertenece. Este ratio indica si un ítem es más caro o más barato en relación con otros ítems de su misma categoría.

De esta manera, medimos cómo fluctúa el precio de un producto durante diferentes estaciones o períodos de tiempo (trimestres en este caso).
"""

#Calculamos la desviación estándar del precio para cada ítem dentro de cada trimestre.
df_seasonal_price_volatility = df_filtered.groupby(['item', 'trimestre'])['sell_price'].std().reset_index()

#Renombramos coluumnas.
df_seasonal_price_volatility = df_seasonal_price_volatility.pivot(index='item', columns='trimestre', values='sell_price')
df_seasonal_price_volatility.columns = ['std_price_T1', 'std_price_T2', 'std_price_T3', 'std_price_T4']
df_seasonal_price_volatility.reset_index(inplace=True)
df_seasonal_price_volatility

"""##Variables relacionadas a crecimiento de ventas

### Crecimiento anual de ventas para cada ítem
Aplicado solo para los años comprendidos entre 2011 y 2015.
"""

#Definimos una función que tiene como objetivo calcular el crecimiento anual de ventas de 2011 a 2015 para cada ítem.
def calculate_annual_sales_growth(df):

  # Filtramos datos para obtener datos soolo del año 2011 hasta 2015.
  df_filtered = df[(df['año'] >= 2011) & (df['año'] <= 2015)]

  #Agrupamos por ítem y año, añadiendo las ventas.
  sales_by_item_year = df_filtered.groupby(['item', 'año'])['ventas'].sum().reset_index()

  #Pivotamos la tabla para tener los años como columnas.
  sales_pivot = sales_by_item_year.pivot(index='item', columns='año', values='ventas')

  #Calculamos la tasa de crecimiento.
  sales_pivot['growth_2012'] = ((sales_pivot[2012] - sales_pivot[2011]) / sales_pivot[2011]) * 100
  sales_pivot['growth_2013'] = ((sales_pivot[2013] - sales_pivot[2012]) / sales_pivot[2012]) * 100
  sales_pivot['growth_2014'] = ((sales_pivot[2014] - sales_pivot[2013]) / sales_pivot[2013]) * 100
  sales_pivot['growth_2015'] = ((sales_pivot[2015] - sales_pivot[2014]) / sales_pivot[2014]) * 100

  return sales_pivot[['growth_2012', 'growth_2013', 'growth_2014', 'growth_2015']]

#Apliacamos la función al dataset df.
df_annual_sales_growth = calculate_annual_sales_growth(df)

df_annual_sales_growth

df_annual_sales_growth.replace([np.inf, -np.inf], np.nan, inplace=True)
df_annual_sales_growth.fillna(0, inplace=True)
df_annual_sales_growth

df_annual_sales_growth['average_growth'] = df_annual_sales_growth.mean(axis=1)
df_annual_sales_growth

"""##Variables relacionadas a eventos

### Ratio de Impacto de Eventos por Trimestre
"""

#Calculamos las ventas totales durante eventos por ítem y trimestre.
event_sales = df_filtered[df_filtered['is_event'] == 1].groupby(['item', 'trimestre'])['ventas'].sum().reset_index()
event_sales.rename(columns={'ventas': 'event_sales'}, inplace=True)

#Calculamos las ventas totales por ítem y trimestre.
total_sales_per_quarter = df_filtered.groupby(['item', 'trimestre'])['ventas'].sum().reset_index()
total_sales_per_quarter.rename(columns={'ventas': 'total_sales_per_quarter'}, inplace=True)

#Unión de las ventas totales con las ventas durante eventos.
df_event_impact = pd.merge(event_sales, total_sales_per_quarter, on=['item', 'trimestre'], how='left')

#Calculamos el ratio de impacto de eventos.
df_event_impact['event_impact_ratio_per_quarter'] = df_event_impact['event_sales'] / df_event_impact['total_sales_per_quarter']

#Reorganizamos el DataFrame con trimestres como columnas.
df_event_impact = df_event_impact.pivot(index='item', columns='trimestre', values='event_impact_ratio_per_quarter')
df_event_impact.rename(columns={1: 'event_impact_ratio_T1', 2: 'event_impact_ratio_T2', 3: 'event_impact_ratio_T3', 4: 'event_impact_ratio_T4'}, inplace=True)

df_event_impact.fillna(0, inplace=True)
df_event_impact.reset_index(inplace=True)
df_event_impact

"""##Merged df: df_features
Combinamos todos los dataframes en uno solo.
"""

df_features = df_total_sales \
    .merge(df_sales_quarter, on='item', how='left') \
    .merge(df_sales_volatility, on='item', how='left') \
    .merge(df_avg_price, on='item', how='left') \
    .merge(df_price_sensitivity, on='item', how='left') \
    .merge(df_seasonal_price_volatility, on='item', how='left') \
    .merge(df_annual_sales_growth, on='item', how='left') \
    .merge(df_event_impact, on='item', how='left')

df_features.set_index('item', inplace=True)

df_features

#Comprobamos que no hayan nulos.
df_features.isnull().sum()

"""---

#ITERACIÓN 1

## IT1. Evaluate Features

### Feature Variance
**Interpret the Results:** If you find features with near-zero variance, consider removing them as they are unlikely to help in differentiating clusters
"""

feature_variances = df_features.var()

print("Feature Variances:\n", feature_variances)

"""### Feature Correlation"""

correlation_matrix = df_features.corr()

plt.figure(figsize=(20, 10))

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)

plt.title("Correlation Matrix Heatmap", fontsize=16)

plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

plt.show()

correlation_matrix = df_features.corr()

print("Feature Correlation Matrix:\n", correlation_matrix)

"""---

## IT1. Estandarizacion de datos
"""

from sklearn.preprocessing import StandardScaler

#Seleccionamos variables para nuestra primera iteracion.
selected_features = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'avg_price',
    'price_sensitivity',
    #'ventas_T1_ratio',
    #'ventas_T2_ratio',
    #'ventas_T3_ratio',
    #'ventas_T4_ratio',
    #'event_impact_ratio_T1',
    #'event_impact_ratio_T2',
    #'event_impact_ratio_T3',
    #'event_impact_ratio_T4',
    'growth_2012',
    'growth_2013',
    'growth_2014',
    'growth_2015',
    'average_growth'
    ]]

selected_features = selected_features.fillna(0)

#Normalizamos datos.
scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""## IT1. Análisis de Componentes Principales (PCA)"""

from sklearn.decomposition import PCA

n_components=6

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

plt.figure(figsize=(8, 5))
plt.bar(range(1, n_components + 1), explained_variance, alpha=0.7, align='center', label='Varianza explicada por componente')
plt.step(range(1, n_components + 1), cumulative_variance, where='mid', label='Varianza acumulada')
plt.xlabel('Componentes principales')
plt.ylabel('Varianza explicada')
plt.title('Varianza explicada por cada componente principal')
plt.legend(loc='best')
plt.show()

"""## IT1. Elbow Curve"""

pca_data_4 = A.iloc[:, :4]

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(pca_data_4)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(K, inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.show()

optimal_k = 4

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(pca_data_4)

df_features['cluster_IT1'] = cluster_labels

plt.figure(figsize=(10, 6))
sns.scatterplot(x=A.iloc[:, 0], y=A.iloc[:, 1], hue=df_features['cluster_IT1'], palette='viridis') # Use .iloc to slice the DataFrame
plt.title('Visualización de Clusters (IT1)')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.show()

"""## IT1. Coeficiente de Silueta"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

silhouette_scores = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    cluster_labels = kmeans.fit_predict(pca_data_4)
    silhouette_avg = silhouette_score(pca_data_4, cluster_labels)
    silhouette_scores.append(silhouette_avg)

plt.figure(figsize=(8, 5))
plt.plot(range(2, 11), silhouette_scores, marker='o')
plt.title('Silhouette Scores for Different k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.show()

"""## IT1. Asignacion de labels"""

optimal_k = 4

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(pca_data_4)

df_features['cluster_IT1'] = cluster_labels

"""## IT1. Fichas"""

features_df = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'avg_price',
    'price_sensitivity',
    #'ventas_T1_ratio',
    #'ventas_T2_ratio',
    #'ventas_T3_ratio',
    #'ventas_T4_ratio',
    #'event_impact_ratio_T1',
    #'event_impact_ratio_T2',
    #'event_impact_ratio_T3',
    #'event_impact_ratio_T4',
    'growth_2012',
    'growth_2013',
    'growth_2014',
    'growth_2015',
    'average_growth',
    'cluster_IT1'
    ]].groupby("cluster_IT1").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

"""---

#ITERACIÓN 2: Enfoque en ventas totales y patrones generales
Propósito: comprender las principales tendencias de ventas, las contribuciones regionales y la distribución trimestral mientras se minimiza el ruido de variables de menor impacto.
"""

df_features = df_total_sales \
    .merge(df_sales_quarter, on='item', how='left') \
    .merge(df_sales_volatility, on='item', how='left') \
    .merge(df_avg_price, on='item', how='left') \
    .merge(df_price_sensitivity, on='item', how='left') \
    .merge(df_seasonal_price_volatility, on='item', how='left') \
    .merge(df_annual_sales_growth, on='item', how='left') \
    .merge(df_event_impact, on='item', how='left')

df_features.set_index('item', inplace=True)

df_features = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    'std_price_T1',
    'std_price_T2',
    'std_price_T3',
    'std_price_T4',
    'avg_price',
    #'precio_relativo',
    'price_sensitivity',
    'event_impact_ratio_T1',
    'event_impact_ratio_T2',
    'event_impact_ratio_T3',
    'event_impact_ratio_T4',
    #'growth_2012',
    #'growth_2013',
    #'growth_2014',
    #'growth_2015',
    #'average_growth'
    ]]

df_features = df_features.fillna(0)
df_features

"""## IT2. Feature Variance"""

feature_variances = df_features.var()

print("Feature Variances:\n", feature_variances)

"""## IT2. Feature Correlation."""

correlation_matrix = df_features.corr()

print("Feature Correlation Matrix:\n", correlation_matrix)

"""## IT2. Estandarización de datos"""

from sklearn.preprocessing import StandardScaler

selected_features = df_features[[
    'total_sales',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'avg_price'
    ]]

selected_features = selected_features.fillna(0)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

selected_features

"""## IT2. Análisis de Componentes Principales (PCA)"""

from sklearn.decomposition import PCA

n_components=6

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

"""## IT2. KMeans"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(A)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(K, inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.show()

optimal_k = 8

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(A)

df_features['cluster_IT2'] = cluster_labels

plt.figure(figsize=(10, 6))
sns.scatterplot(x=A.iloc[:, 0], y=A.iloc[:, 1], hue=df_features['cluster_IT2'], palette='viridis') # Use .iloc to slice the DataFrame
plt.title('Visualización de Clusters (IT2)')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.show()

"""## IT2. Fichas"""

features_df = df_features[[
    'total_sales',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'avg_price',
    'cluster_IT2'
    ]].groupby("cluster_IT2").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

"""---

# ITERACIÓN 3: Enfoque en dinámicas de ventas regionales y estacionales
Propósito: Concéntrese en la dinámica de las ventas en todas las regiones y temporadas, entendiendo qué artículos funcionan mejor en determinadas áreas o períodos.

## IT3. Estandarización de datos
"""

df_features = df_total_sales \
    .merge(df_sales_quarter, on='item', how='left') \
    .merge(df_sales_volatility, on='item', how='left') \
    .merge(df_avg_price, on='item', how='left') \
    .merge(df_price_sensitivity, on='item', how='left') \
    .merge(df_seasonal_price_volatility, on='item', how='left') \
    .merge(df_annual_sales_growth, on='item', how='left') \
    .merge(df_event_impact, on='item', how='left')

df_features.set_index('item', inplace=True)

from sklearn.preprocessing import StandardScaler

selected_features = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    'event_impact_ratio_T1',
    'event_impact_ratio_T2',
    'event_impact_ratio_T3',
    'event_impact_ratio_T4',
    ]]

selected_features = selected_features.fillna(0)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""## IT3. Análisis de Componentes Principales (PCA)"""

from sklearn.decomposition import PCA

n_components=6

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

"""## IT3. KMeans"""

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(A)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(K, inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.show()

from sklearn.cluster import KMeans

optimal_k = 6

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(A)

df_features['cluster_IT3'] = cluster_labels

"""## IT3. Fichas"""

features_df = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    'event_impact_ratio_T1',
    'event_impact_ratio_T2',
    'event_impact_ratio_T3',
    'event_impact_ratio_T4',
    'cluster_IT3'
    ]].groupby("cluster_IT3").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

"""---

#ITERACIÓN 4: Enfoque en la sensibilidad de precio y el impacto de eventos
Propósito: comprender la relación entre los cambios de precios, las ventas impulsadas por eventos y la sensibilidad general al precio, lo que ayuda a optimizar las estrategias de precios y promociones.

## IT4. Estandarización de datos
"""

df_features = df_total_sales \
    .merge(df_sales_quarter, on='item', how='left') \
    .merge(df_sales_volatility, on='item', how='left') \
    .merge(df_avg_price, on='item', how='left') \
    .merge(df_price_sensitivity, on='item', how='left') \
    .merge(df_seasonal_price_volatility, on='item', how='left') \
    .merge(df_annual_sales_growth, on='item', how='left') \
    .merge(df_event_impact, on='item', how='left')

df_features.set_index('item', inplace=True)

from sklearn.preprocessing import StandardScaler

selected_features = df_features[[
    'total_sales',
    'avg_price',
    'std_price_T1',
    'std_price_T2',
    'std_price_T3',
    'std_price_T4',
    'price_sensitivity',
    'event_impact_ratio_T1',
    'event_impact_ratio_T2',
    'event_impact_ratio_T3',
    'event_impact_ratio_T4'
    ]]

selected_features = selected_features.fillna(0)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""## IT4. Análisis de Componentes Principales (PCA)"""

from sklearn.decomposition import PCA

n_components=6

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

"""## IT4. KMeans"""

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(A)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(K, inertia, marker='o')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.show()

from sklearn.cluster import KMeans

optimal_k = 6

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(A)

df_features['cluster_IT4'] = cluster_labels

df_features

"""## IT4. Fichas"""

features_df = df_features[[
    'total_sales',
    'avg_price',
    'std_price_T1',
    'std_price_T2',
    'std_price_T3',
    'std_price_T4',
    'price_sensitivity',
    'event_impact_ratio_T1',
    'event_impact_ratio_T2',
    'event_impact_ratio_T3',
    'event_impact_ratio_T4',
    'cluster_IT4'
    ]].groupby("cluster_IT4").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

"""# ITERACIÓN 5: Enfoque en ventas desde una perspectiva de crecimiento.

## IT5. Merged df: df_features
"""

df_features = df_total_sales \
    .merge(df_sales_quarter, on='item', how='left') \
    .merge(df_sales_volatility, on='item', how='left') \
    .merge(df_avg_price, on='item', how='left') \
    .merge(df_price_sensitivity, on='item', how='left') \
    .merge(df_seasonal_price_volatility, on='item', how='left') \
    .merge(df_annual_sales_growth, on='item', how='left') \
    .merge(df_event_impact, on='item', how='left')

df_features.set_index('item', inplace=True)

df_features

from sklearn.preprocessing import StandardScaler

#Seleccionamos variables para nuestra primera iteracion.
df_features = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    'ventas_T1_ratio',
    'ventas_T2_ratio',
    'ventas_T3_ratio',
    'ventas_T4_ratio',
    #'std_price_T1',
    #'std_price_T2',
    #'std_price_T3',
    #'std_price_T4',
    'avg_price',
    #'price_sensitivity',
    #'event_impact_ratio_T1',
    #'event_impact_ratio_T2',
    #'event_impact_ratio_T3',
    #'event_impact_ratio_T4',
    #'growth_2012',
    #'growth_2013',
    #'growth_2014',
    #'growth_2015',
    'average_growth',
    ]]

selected_features = selected_features.fillna(0)

#Normalizamos datos.
scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""## IT5. Feature Variance"""

feature_variances = df_features.var()

print("Feature Variances:\n", feature_variances)

"""## IT5. Feature Correlation"""

correlation_matrix = df_features.corr()

print("Feature Correlation Matrix:\n", correlation_matrix)

"""## IT5. Estandarización de datos"""

from sklearn.preprocessing import StandardScaler

selected_features = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    #'ventas_T1_ratio',
    #'ventas_T2_ratio',
    #'ventas_T3_ratio',
    'ventas_T4_ratio',
    #'std_price_T1',
    #'std_price_T2',
    #'std_price_T3',
    #'std_price_T4',
    'avg_price',
    #'price_sensitivity',
    #'event_impact_ratio_T1',
    #'event_impact_ratio_T2',
    #'event_impact_ratio_T3',
    #'event_impact_ratio_T4',
    #'growth_2012',
    #'growth_2013',
    #'growth_2014',
    #'growth_2015',
    'average_growth',
    ]]

# Handle missing values if necessary
selected_features = selected_features.fillna(0)  # or use another method to handle NaNs

# Normalize features
scaler = StandardScaler()
scaled_features = scaler.fit_transform(selected_features)

"""## IT5. Análisis de Componentes Principales (PCA)"""

from sklearn.decomposition import PCA

n_components=5

pca = PCA(n_components)
A = pca.fit_transform(scaled_features)

explained_variance = pca.explained_variance_ratio_
print("Varianza explicada por cada componente:", explained_variance)

cumulative_variance = explained_variance.cumsum()
exp_var_ratio_sum = sum(explained_variance)

print(f"Con {n_components} componentes, explicamos el {exp_var_ratio_sum*100:.2f}% de la varianza original.")

"""## IT5. KMeans

## IT5. Elbow Curve
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

range_n_clusters = range(1, 21)

inertia = []

for n_clusters in range_n_clusters:
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    kmeans.fit(A)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range_n_clusters, inertia, marker='o')
plt.title('Método del Codo para Determinar el Número de Clusters')
plt.xlabel('Número de Clusters')
plt.ylabel('Inertia')
plt.show()

optimal_k = 7

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans_final.fit_predict(A)

df_features['cluster_IT5'] = cluster_labels

plt.figure(figsize=(10, 6))
sns.scatterplot(x=A.iloc[:, 0], y=A.iloc[:, 1], hue=df_features['cluster_IT5'], palette='viridis')
plt.title('Visualización de Clusters (IT5)')
plt.xlabel('Componente Principal 1')
plt.ylabel('Componente Principal 2')
plt.show()

"""## IT5. Silhouette Coefficient"""

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

range_n_clusters = range(2, 11)

silhouette_avg = []

for n_clusters in range_n_clusters:
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    cluster_labels = kmeans.fit_predict(A)
    silhouette_avg.append(silhouette_score(A, cluster_labels))

plt.figure(figsize=(8, 5))
plt.plot(range_n_clusters, silhouette_avg, marker='o')
plt.title('Método de la Silueta para Determinar el Número de Clusters')
plt.xlabel('Número de Clusters')
plt.ylabel('Coeficiente de Silueta Promedio')
plt.show()

df_features

"""## IT5. Fichas"""

features_df = df_features[[
    'total_sales',
    'ratio_ventas_Boston',
    'ratio_ventas_Nueva_York',
    'ratio_ventas_Filadelfia',
    #'ventas_T1_ratio',
    #'ventas_T2_ratio',
    #'ventas_T3_ratio',
    'ventas_T4_ratio',
    #'std_price_T1',
    #'std_price_T2',
    #'std_price_T3',
    #'std_price_T4',
    'avg_price',
    #'price_sensitivity',
    #'event_impact_ratio_T1',
    #'event_impact_ratio_T2',
    #'event_impact_ratio_T3',
    #'event_impact_ratio_T4',
    #'growth_2012',
    #'growth_2013',
    #'growth_2014',
    #'growth_2015',
    'average_growth',
    'cluster_IT5'
    ]].groupby("cluster_IT5").describe().T

features_df.style.background_gradient(cmap = 'Blues', axis = 1)

df_features[df_features['cluster_5']==3]

df_filtered[df_filtered['item']=='SUPERMARKET_3_064']

df_filtered[df_filtered['item'] == 'SUPERMARKET_3_064'].groupby(['item', 'año'])['ventas'].sum()