# -*- coding: utf-8 -*-
"""TimeSeries_Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkjXXLcQWtPEeAILBVgjSkxkXyfNJEW3

# Forecasting DSMarket

## Objetivo

*   Desarrollar un nuevo enfoque de pronóstico para casos de uso que dependen de la precisión del pronóstico (modelo predictivo).

*   Confirme si su enfoque es válido: generalmente comienzan prediciendo las ventas a nivel de tienda-producto y, para obtener ventas agregadas por departamento/tienda/ciudad, suman predicciones independientes. Comience con predicciones de 28 días (4 semanas).

*   Utilice el formato de salida que me enviaron para evaluar modelos.
"""

# Commented out IPython magic to ensure Python compatibility.
# imports time series
import pandas as pd
import numpy as np
import time

# plots
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
# %matplotlib inline
import seaborn as sns


# para calculas métricas del modelo
from sklearn.metrics import mean_squared_error

# misc
import os
import time
import itertools
import warnings
warnings.filterwarnings("ignore")

# apartado ts
!pip install statsmodels
!pip install xgboost
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.holtwinters import SimpleExpSmoothing, ExponentialSmoothing, Holt
from sklearn.model_selection import GridSearchCV
import xgboost as xgb


!pip install prophet
from prophet import Prophet

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = os.path.join("/content/drive/MyDrive/Nuclio/Notebooks/CapstoneProject/CSVs/DatosAgrupadosEnSemanas.csv.gz")

df = pd.read_csv(DATA_PATH)

df.head()

# Convertiremos la columna de "yearweek" a formato datetime para realizar tareas de forecasting
# para ello necesitamos que la columna este en formato string primero y despues la cambiaremos a Datetime
df['yearweek'] = df['yearweek'].astype(str)

# Convertir 'yearweek' a datetime usando el primer día de la semana
df['date'] = pd.to_datetime(df['yearweek'] + '1', format='%Y%W%w')  # El 1 agrega el primer día de la semana (lunes)

# Mostrar el DataFrame con la nueva columna de fechas
df.head()

"""##EDA del dataset"""

df['id'].nunique()

df['date'].nunique()

df['department'].unique()

df['category'].unique()

df['item'].nunique() # Tenemos 3049 items unicos con los que hacer timeseries

# Contar cuántas tiendas únicas hay en cada región
stores_por_region = df.groupby('region')['store'].unique().apply(list)
# Mostrar el resultado
print(stores_por_region)

MIN_DATE = df["date"].min()
MAX_DATE = df["date"].max()
print(f"Min date is {MIN_DATE}\nMax date is {MAX_DATE}")

# Nuevo orden de las columnas. Al no reindexar la columna "yearweek" desaparece del datasset
orden_columns = ['id','item','category','department','store','region','store_code','event','date','semana','trimestre','año','ventas','sell_price']

# Reordenar el DataFrame usando reindex
df = df.reindex(columns=orden_columns)

df.set_index("date")["ventas"].plot(style= ".", figsize=(15,5), title= "Historico de Ventas Totales" )
plt.show()

#Historico por region
ny = df[df["region"] == "New York"].set_index("date")["ventas"]
ph = df[df["region"] == "Philadelphia"].set_index("date")["ventas"]
bos = df[df["region"] == "Boston"].set_index("date")["ventas"]

fig, ax = plt.subplots(figsize=(15, 5))
ny.plot(ax = ax, label = "New York")
ph.plot(ax = ax, label = "Philadelphia")
bos.plot(ax = ax, label = "Boston")
ax.legend(loc = "upper left")

# Agrupar las ventas por año para cada región
ny = df[df["region"] == "New York"].groupby('año')["ventas"].sum()
ph = df[df["region"] == "Philadelphia"].groupby('año')["ventas"].sum()
bos = df[df["region"] == "Boston"].groupby('año')["ventas"].sum()

# Crear un DataFrame combinado para facilitar el gráfico
df_combined = pd.DataFrame({
    "New York": ny,
    "Philadelphia": ph,
    "Boston": bos
})

# Graficar las barras
fig, ax = plt.subplots(figsize=(10, 5))
df_combined.plot(kind='bar', ax=ax)

# Configurar leyenda y etiquetas
ax.set_ylabel('Ventas')
ax.set_xlabel('Año')
ax.set_title('Ventas por año en diferentes regiones')
plt.xticks(rotation=0)
ax.legend(loc="upper left")
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x):,}'))
# Mostrar gráfico
plt.show()

def plot_ts_acf_pacf(y, title):
    '''
    Plots the ts you pass and the acf and pacf.
    Plotea los graficos para identificar
    '''
    fig = plt.figure(figsize = (12, 10))
    ax1, ax2, ax3 = fig.subplots(3, 1)

    ax1.plot(y)
    ax1.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: int(x)))  # Formato de enteros para el eje Y
    plot_acf(x = y, ax = ax2, lags = 14)
    plot_pacf(x = y, ax = ax3, lags = 14)

    plt.suptitle(t = title, fontsize = 20)

y = df.set_index("date").resample("M")["ventas"].sum()
plot_ts_acf_pacf(y = y, title = "Monthly Sales for all items in all shops");

(
    df.
    groupby(["store"])
    ["ventas"].sum()
    .sort_values(ascending = False)
    .plot(kind = "bar", figsize = (12, 4))
);
ax = plt.gca()  # Obtener los ejes actuales
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x):,}'))

plt.show()

(
    df.
    groupby(["department"])
    ["ventas"].sum()
    .sort_values(ascending = False)
    .plot(kind = "bar", figsize = (8, 4))
);
ax = plt.gca()  # Obtener los ejes actuales
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x):,}'))

plt.show()

"""##Adaptamos el dataset al objetivo de la tarea"""

df2 = df.copy()

df2['revenue']=df2['ventas'] * df2['sell_price'] #creamos la variable revenue (facturación)

# utiliza ultimo caracter de department

df2['department'] = df2['department'].str[-1].astype(int)

df2['item'] = df2['item'].str[-3:].astype(int) #Nos quedamos con el numero del item

# Vamos a prescindir de diferentes colummnas ya que existen otras mas relevantes o estan formadas por la
# agregacion de otras existentes.
cols_drop= ['store_code']

df2.drop(cols_drop, axis=1,inplace=True)

# Definir el mapeo manual
region_mapping = {
    'New York': 1,
    'Philadelphia': 2,
    'Boston': 3
}

# Asignar el orden numérico manualmente
df2['region'] = df2['region'].map(region_mapping).astype("int64")

# Definir el mapeo manual
store_mapping = {
    'Greenwich_Village': 0,
    'Harlem': 1,
    'Tribeca': 2,
    'Brooklyn': 3,
    'Midtown_Village': 4,
    'Yorktown': 5,
    'Queen_Village': 6,
    'South_End': 7,
    'Roxbury': 8,
    'Back_Bay': 9,
}

# Asignar el orden numérico manualmente a la columna 'store'
df2['store'] = df2['store'].map(store_mapping).astype("int64")

# Definir el mapeo manual
dptm_mapping = {
    'ACCESORIES': 0,
    'HOME_&_GARDEN': 1,
    'SUPERMARKET': 2

}

# Asignar el orden numérico manualmente a la columna 'store'
df2['category'] = df2['category'].map(dptm_mapping).astype("int64")

# Definir el mapeo manual
eve_mapping = {
    'Sin_Evento': 0,
    'SuperBowl': 1,
    'Ramadan starts': 2,
    'Thanksgiving': 3,
    'NewYear': 4,
    'Easter': 5
}

# Asignar el orden numérico manualmente a la columna 'store'
df2['event'] = df2['event'].map(eve_mapping).astype("int64")

"""Creamos las 4 semanas extras que necesitamos de mayo para hacer la prediccion"""

df3 = df2.copy()

last_date = df3["date"].max()

# Generamos nuevas fechas
new_dates = pd.date_range(start=last_date + pd.Timedelta(days=7), periods=4, freq="W-MON")

new_dates

last_records = df3.groupby('id').last().reset_index()

new_rows = last_records.loc[last_records.index.repeat(len(new_dates))]
new_rows['date'] = list(new_dates) * len(last_records)
new_rows['ventas'] = 0
new_rows['revenue'] = 0
new_rows['semana'] = new_rows['date'].dt.isocalendar().week
new_rows['trimestre'] = new_rows['date'].dt.quarter
new_rows['año'] = new_rows['date'].dt.year

df_future = pd.concat([df3, new_rows], ignore_index=True)

df_future[df_future['id']=='SUPERMARKET_1_001_BOS_1'].tail(10)

df_future.shape

"""##Creacion de features"""

df_it_st2 = df_future.copy()

df_it_st2.head()

# Fuente del descubrimiento: https://www.kaggle.com/code/lauraportell/future-sales-part-ii-model-training-2/notebook
class FeatureGenerator(object):
    '''
    Esto es una clase, nos servirá para montar una especie de "librería" de funciones
    propia para crear nuestras variables customizadas para mejorar nuestro dataset de TimeSeries.
    '''

    def __init__(self, full_df, gb_list):
        '''
        Se inicializa pasando un DataFrame y un listado de columnas las cuales nos servirán
        para generar nuevas variables. La última línea de esta función es para renombrar las
        columnas nuevas y añadirlas al DataFrame.
        '''
        self.full_df = full_df
        self.gb_list = gb_list
        self.objective_column_name = "_".join(gb_list)

    def generate_gb_df(self):
        '''
        Agrupamos el DataFrame original y calculamos sumas y medias de 'ventas' por cada grupo.
        El resultado es un DataFrame con características agregadas que pueden ayudar a identificar tendencias.
        '''
        def my_agg(full_df_, args):
            names = {
                '{}_sum'.format(args): full_df_['ventas'].sum(),
                '{}_mean'.format(args): full_df_['ventas'].mean(),
            }
            return pd.Series(names)

        # Aplicar la función agregada
        gb_df_ = self.full_df.groupby(self.gb_list).apply(my_agg, args=self.objective_column_name).reset_index()
        self.gb_df_ = gb_df_

    def generate_shift_features(self, suffix):
        '''
        Crea características retrasadas (lags) y variaciones de las mismas.
        '''
        name_ = self.objective_column_name + "_" + suffix

        for i in range(1, 4):
            # Crear la característica shift
            self.gb_df_['{}_shift_{}'.format(name_, i)] = self.gb_df_.groupby(self.gb_list[1:])[name_].transform(lambda series: series.shift(i))

            # Crear la variación porcentual, solo para los primeros 3 lags
            self.gb_df_['{}_var_pct_{}'.format(name_, i)] = self.gb_df_.groupby(self.gb_list[1:])[name_].transform(lambda series: (series - series.shift(i)) / series.shift(i))

        # Reemplazar NaN, inf, -inf
        self.gb_df_.fillna(-1, inplace=True)
        self.gb_df_.replace([np.inf, -np.inf], -1, inplace=True)

    def return_gb_df(self):
        '''
        Retorna el DataFrame con las características shift y variacion generadas.
        '''
        self.generate_shift_features(suffix="sum")
        self.generate_shift_features(suffix="mean")

        return self.gb_df_

def crear_lag_features(df, gb_list):
    var_gen = FeatureGenerator(df, ['date'] + gb_list)
    var_gen.generate_gb_df()
    store_var_gen = var_gen.return_gb_df()
    df = pd.merge(df, store_var_gen, on=["date"] + gb_list, how="left")
    return df

features_lags_params= [
    {   #Totales y lags de Tienda
        "gb_list" : ["store"],
    },
    {   #Totales y lags de
        "gb_list" : ["store","region"],
    },
    {   #Totales y lags de
        "gb_list" : ["store","category","department"],
    },
    {   #Totales y lags de Ciudad
        "gb_list" : ["region"],
    },
    {   #Totales y lags de
        "gb_list" : ["region","category","department"],
    },
    {   #Totales y lags de Departamento
        "gb_list" : ["category","department"],
    },



]

start_time = time.time()

print(df_it_st2.shape)

n_var_old = len(df_it_st2.columns)

#Generar nuevas features
for params in features_lags_params:
    df_it_st2 = crear_lag_features(df_it_st2, params["gb_list"])

n_var_new = len(df_it_st2.columns)

end_time = time.time()
elapsed_time = end_time - start_time

print('-'*30)
print(df_it_st2.shape)
print(f"Se crearon {n_var_new - n_var_old} nuevas variables")
print(f"El tiempo de ejecución fue: {elapsed_time/60:.2f} minutos")
print('-'*30)

df_it_st2.info()

"""## Train/Test Split"""

df_it_st3 =  df_it_st2.copy()

df_it_st3.head(3)

df_it_st3.columns.tolist()

cols_drop = [
    "trimestre",
    "revenue",
    "department",

]

df_it_st3.drop(cols_drop, inplace = True, axis = 1)

df_it_st3.set_index("id", inplace = True)

df_it_st3.sample(5)

#Convertir las variables al tipo de dato menos pesado posible
for col in df_it_st3.select_dtypes(include=['int']):
    df_it_st3[col] = pd.to_numeric(df_it_st3[col], downcast='integer')

for col in df_it_st3.select_dtypes(include=['float']):
  df_it_st3[col] = pd.to_numeric(df_it_st3[col], downcast='float')

df_it_st3.info()

train_index = sorted(list(df_it_st3["date"][df_it_st3["date"].dt.year <= 2014].unique()))

valida_index = sorted(list(df_it_st3["date"][(df_it_st3["date"].dt.year > 2014) & (df_it_st3["date"].dt.year < 2016)].unique()))

test_index = sorted(list(df_it_st3["date"][df_it_st3["date"].dt.year > 2015].unique()))##[:-4]))

##pred_index = sorted(list(df_it_st3["date"][df_it_st3["date"].dt.year > 2015].unique()[-4:]))

print(f"Our train index is {train_index[0]} - ... - {train_index[-1]}\n")
print(f"Our validation index is {valida_index[0]} - ... - {valida_index[-1]}\n")
print(f"Our test index is {test_index[0]} - ... - {test_index[-1]}\n")

##print(f"Our prediction index is {pred_index[0]} - ... - {pred_index[-1]}")

X_train = df_it_st3[df_it_st3["date"].isin(train_index)].drop(['ventas', "date"], axis=1)
Y_train = df_it_st3[df_it_st3["date"].isin(train_index)]['ventas']

X_valida = df_it_st3[df_it_st3["date"].isin(valida_index)].drop(['ventas', "date"], axis=1)
Y_valida = df_it_st3[df_it_st3["date"].isin(valida_index)]['ventas']

X_test = df_it_st3[df_it_st3["date"].isin(test_index)].drop(['ventas', "date"], axis = 1)
Y_test = df_it_st3[df_it_st3["date"].isin(test_index)]['ventas']

##X_pred = df_it_st3[df_it_st3["date"].isin(pred_index)].drop(['ventas', "date"], axis=1)
##Y_pred = df_it_st3[df_it_st3["date"].isin(pred_index)]['ventas']

X_train.head()

Y_train.head()

X_test.head()

Y_test.head()

# Como Y_test esta llena, crearemos una copia y la utilizaremos para evaluar la prediccion.

Y_test_eval = Y_test.copy()

Y_test[:] = 0

Y_test.head()

Y_test.sum()

"""##Entrenamiento y Evaluacion del modelo

###Busqueda de parámetros
"""

# Antes de entrenar nuestro modelo final, utilizaremos la funcion GridSearch, para encontrar los parametros que funciolnen mejor con nuestro modelo.

start_time = time.time() #Inicializamos un contador para saber cuanto dura la ejecucion.

xgbgs = xgb.XGBRegressor(random_state = 239)

parameters = {
    'objective':['reg:linear'],
    'learning_rate': [0.04,0.1,0.2],
    'max_depth': [5,10,15],
    'n_estimators': [300,500,1000],

    }

xgb_grid = GridSearchCV(xgbgs,
                        parameters,
                        scoring='neg_mean_squared_error',
                        cv = 5,
                        n_jobs = 5,
                        verbose=True)


xgb_grid.fit(X_train, Y_train)

end_time = time.time()
elapsed_time = end_time - start_time

# Imprimimos los mejores parámetros y el mejor puntaje (que será el MSE negativo)
print(f"Mejores parámetros: {xgb_grid.best_params_}")
print(f"Mejor puntaje (MSE negativo): {xgb_grid.best_score_}")
print(f"El tiempo de ejecución fue: {elapsed_time/60:.2f} minutos")

# El mejor modelo está ahora en rnd_search.best_estimator_
best_model = xgb_grid.best_estimator_

# Podemos evaluar este modelo en el conjunto de validación
Y_valida_pred = best_model.predict(X_valida)

"""###Entrenamiento"""

model = xgb.XGBRegressor(eval_metric = "rmse",
                         seed = 239,
                         learning_rate= 0.04,
                         max_depth= 15,
                         n_estimators= 1000,
                         objective= "reg:linear",
                         early_stopping_rounds=20
                         )

model.fit(
    X_train,
    Y_train,
    eval_set = [(X_train, Y_train), (X_valida, Y_valida)],
    verbose = True,
)

X_test

"""###Peso de las variables"""

fi = pd.DataFrame(data=model.feature_importances_,
             index=model.feature_names_in_,
             columns=['importance'])

fi.sort_values(by='importance').plot(kind='barh', figsize=(10, 10), title='Feature Importance')
plt.show()

"""###Evaluacion de Preduccion"""

X_test.info()

if "ventas" in X_test.columns:
    X_test.drop("ventas", axis = 1, inplace = True)

Y_test_predict = model.predict(X_test)
X_test["ventas"] = Y_test_predict

Y_test_predict

X_test.reset_index(inplace = True)

X_test['ventas'].head(3)

X_test_eval = X_test.copy()

Y_test_eval.head()

X_test_eval.head()

Y_test_eval.shape

X_test_eval.shape

# Asegurándote de que Y_test_eval es una Serie
Y_test_eval = Y_test_eval.reset_index(drop=True)

# Concatenar Y_test_eval como una nueva columna en X_test_eval
df_eval = pd.concat([X_test_eval.reset_index(drop=True), Y_test_eval], axis=1)

df_eval.head(5)

# Renombrar la columna de la serie (por ejemplo, a "ventas_y")
df_eval.columns = list(X_test_eval.columns) + ["ventas_reales"]
df_eval.rename(columns={'ventas': 'ventas_predict'}, inplace=True)
# Mostrar el dataframe
df_eval.head()

df_eval.shape

X_test_eval.head(3)

df_eval["error"] = df_eval["ventas_predict"] -  df_eval["ventas_reales"]

df_eval["error"].mean()# de media, el modelo a predicho las ventas con un error del 0.37

Y_train_predict = model.predict(X_train)
Y_valida_predict = model.predict(X_valida)

rmse_train = np.sqrt(
    mean_squared_error(
        y_true = Y_train,
        y_pred = Y_train_predict
    )
)

rmse_valida = np.sqrt(
    mean_squared_error(
        y_true = Y_valida,
        y_pred = Y_valida_predict
    )
)

rmse_train= (round(rmse_train, 3))
rmse_test = (round(rmse_valida, 3))

print(f"Train RMSE: {rmse_train}")
print(f"Validation RMSE: {rmse_valida}")

df_it_st3["ventas"].mean()

"""## Graficas de validacion de la prediccion"""

df_eval['yearweek'] = df_eval['año'].astype(str) + '-' + df_eval['semana'].astype(str).str.zfill(2)
df_eval['date'] = pd.to_datetime(df_eval['yearweek'] + '-1', format='%Y-%W-%w')

df_eval.set_index("date", inplace = True)

df_eval.tail()

ax = df_eval[["ventas_reales"]].plot(figsize=(10, 5), style=".", label="Ventas Reales")
df_eval["ventas_predict"].plot(ax=ax, style=".", label="Predicciones")
plt.legend(["VentasReales","Predicciones"])
ax.set_title("Ventas reales V.S Prediccion")
plt.show()

# Creamos un Dataframe exclusivo para realizar los graficos de dispersion y el histograma de residuos
validacion_pred = pd.DataFrame({
    'Ventas Actuales': Y_valida,
    'Ventas Prediccion': Y_valida_predict
})

validacion_pred['Residuos'] = validacion_pred['Ventas Actuales'] - validacion_pred['Ventas Prediccion']
validacion_pred.head()

# Gráfico de dispersión de las predicciones vs valores reales
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Ventas Actuales', y='Ventas Prediccion', data=validacion_pred)
plt.plot([validacion_pred['Ventas Actuales'].min(), validacion_pred['Ventas Actuales'].max()],
         [validacion_pred['Ventas Actuales'].min(), validacion_pred['Ventas Actuales'].max()],
         color='red', linestyle='--')  # Línea de perfecta predicción
plt.title('Ventas Actualesredicted Sales - Validation Set')
plt.xlabel('Ventas Actuales')
plt.ylabel('Ventas Prediccion')
plt.show()

# Histograma de residuos
plt.figure(figsize=(10, 6))
sns.histplot(validacion_pred['Residuos'], kde=True, color='blue')
plt.title('Distribucion de Errores - Validacion')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.show()

"""## Prediccion de los siguiente 28 días (4 semanas)

###Generamos un dataset para graficar la prediccion
"""

df_eval

df_eval.reset_index(inplace = True)

columns=['id', 'item', 'category', 'store', 'region', 'event',
       'semana', 'año','date', 'sell_price', 'ventas_predict', 'ventas_reales']

# Creamos el Dataset de mayo con sus predicciones.
df_4weeks = df_eval[columns][df_eval['date'] >= '2016-04-25']

df_4weeks

df_4weeks[df_4weeks['id']=='ACCESORIES_1_001_BOS_1']

"""### Se transforman las variables para ser mas legibles"""

# Creamos Datasets con las prediciones y valores reales del mes de Abril para tomar de referencia en la calidad de nuestro modelo

ventas_abril = df_eval[df_eval['date'].dt.month == 4]

# Primero vamos a agrupar las ventas reales por las variables que utilizaremos para el control de la prediccion
ventas_por_categoria_abril = ventas_abril.groupby('category')['ventas_reales'].sum().reset_index()
ventas_por_region_abril = ventas_abril.groupby('region')['ventas_reales'].sum().reset_index()
ventas_por_tienda_abril = ventas_abril.groupby('store')['ventas_reales'].sum().reset_index()

# Luego hacemos lo mismo que anteriormente pero con las ventas que hemos predecido
pred_por_categoria_abril = ventas_abril.groupby('category')['ventas_predict'].sum().reset_index()
pred_por_region_abril = ventas_abril.groupby('region')['ventas_predict'].sum().reset_index()
pred_por_store_abril = ventas_abril.groupby('store')['ventas_predict'].sum().reset_index()

# Por ultimo, hacemos un merge de lo que hemos creado para poder visualizarlo en graficos
merged_df = pd.merge(pred_por_categoria_abril, ventas_por_categoria_abril, on='category', suffixes=('_predict', '_reales'))
merged_df_region = pd.merge(pred_por_region_abril, ventas_por_region_abril, on='region', suffixes=('_predict', '_reales'))
merged_df_store = pd.merge(pred_por_store_abril, ventas_por_tienda_abril, on='store', suffixes=('_predict', '_reales'))

# El ultimo paso es crear la variable de la diferencia entre lo predecido y las ventas reales.
merged_df['diferencia'] = merged_df['ventas_predict'] - merged_df['ventas_reales']
merged_df_region['diferencia'] = merged_df_region['ventas_predict'] - merged_df_region['ventas_reales']
merged_df_store['diferencia'] = merged_df_store['ventas_predict'] - merged_df_store['ventas_reales']

# Hardcodeamos las variables de nuevo para hecer más entendible los graficos que haremos a continuacion
# Definir el mapeo manual
region_mapping = {
    1: 'New York',
    2: 'Philadelphia',
    3: 'Boston'
}

# Asignar el orden numérico manualmente
df_4weeks['region'] = df_4weeks['region'].map(region_mapping).astype("str")
merged_df_region['region'] = merged_df_region['region'].map(region_mapping).astype("str")

# Definir el mapeo manual
store_mapping = {
    0: 'Greenwich_Village',
    1: 'Harlem',
    2: 'Tribeca',
    3: 'Brooklyn',
    4: 'Midtown_Village',
    5: 'Yorktown',
    6: 'Queen_Village',
    7: 'South_End',
    8: 'Roxbury',
    9: 'Back_Bay'
}

# Asignar el orden numérico manualmente a la columna 'store'
df_4weeks['store'] = df_4weeks['store'].map(store_mapping).astype("str")
merged_df_store['store'] = merged_df_store['store'].map(store_mapping).astype("str")

# Definir el mapeo manual
dptm_mapping = {
    0 : 'ACCESORIES',
    1 : 'HOME_&_GARDEN',
    2 : 'SUPERMARKET'

}

# Asignar el orden numérico manualmente a la columna 'category'
df_4weeks['category'] = df_4weeks['category'].map(dptm_mapping).astype("str")
merged_df['category'] = merged_df['category'].map(dptm_mapping).astype("str")

# Definir el mapeo manual
eve_mapping = {
    0 : 'Sin_Evento',
    1 : 'SuperBowl',
    2 : 'Ramadan starts',
    3 : 'Thanksgiving',
    4 : 'NewYear',
    5 : 'Easter'
}

# Asignar el orden numérico manualmente a la columna 'event'
df_4weeks['event'] = df_4weeks['event'].map(eve_mapping).astype("str")

df_4weeks.info()

"""### Representacion de las predicciones"""

df_4weeks.groupby(['store','date'])['ventas_predict'].sum()

df_4weeks["ventas_predict"].plot(figsize=(12, 6),
                                 ms=1,
                                 lw=1, title="Ventas Prediccion item")
plt.show()

# Agrupar las ventas por tienda y sumarlas
ventas_por_tienda = df_4weeks.groupby('store')['ventas_predict'].sum()

# Crear el gráfico de barras
plt.figure(figsize=(12, 6))
bars = plt.bar(ventas_por_tienda.index, ventas_por_tienda.values)
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, round(yval, 2), ha='center', va='bottom', fontsize=10)

plt.xlabel('Tienda')
plt.ylabel('Ventas Totales')
plt.title('Ventas por Tienda')
plt.xticks(rotation=45, ha='right')  # Rotar las etiquetas del eje x para una mejor legibilidad
plt.tight_layout()  # Ajustar el diseño del gráfico
plt.show()

# Agrupar las ventas por Region y sumarlas
ventas_por_region = df_4weeks.groupby('region')['ventas_predict'].sum()

# Crear el gráfico de barras
plt.figure(figsize=(12, 6))
bars = plt.bar(ventas_por_region.index, ventas_por_region.values)
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, round(yval, 2), ha='center', va='bottom', fontsize=10)

plt.xlabel('Region')
plt.ylabel('Ventas Totales')
plt.title('Ventas por Region')
plt.xticks(rotation=45, ha='right')  # Rotar las etiquetas del eje x para una mejor legibilidad
plt.tight_layout()  # Ajustar el diseño del gráfico
plt.show()

# Agrupar las ventas por category y sumarlas
ventas_por_category = df_4weeks.groupby('category')['ventas_predict'].sum()

# Crear el gráfico de barras
plt.figure(figsize=(12, 6))
bars = plt.bar(ventas_por_category.index, ventas_por_category.values)
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, round(yval, 2), ha='center', va='bottom', fontsize=10)

plt.xlabel('category')
plt.ylabel('Ventas Totales')
plt.title('Ventas por category')
plt.xticks(rotation=45, ha='right')  # Rotar las etiquetas del eje x para una mejor legibilidad
plt.tight_layout()  # Ajustar el diseño del gráfico
plt.show()

df_4weeks.set_index("date", inplace = True)

columns=['id', 'item', 'category', 'department', 'store', 'region', 'event',
       'semana', 'trimestre', 'año','date', 'sell_price', 'ventas_predict', 'ventas_reales']

df_4weeks.info()

df_4weeks

df_4weeks.reset_index(inplace = True)

# Crear el gráfico de barras apiladas
fig, ax = plt.subplots(figsize=(10, 6))

# Barras para las ventas reales
ax.bar(merged_df['category'], merged_df['ventas_reales'], label='Ventas Reales')

# Barras para las ventas predichas (apiladas sobre las reales)
ax.bar(merged_df['category'], merged_df['ventas_predict'], bottom=merged_df['ventas_reales'], label='Ventas Predichas')

# Añadir etiquetas con el porcentaje de diferencia
for i, row in merged_df.iterrows():
    total_ventas = row['ventas_reales'] + row['ventas_predict']
    diferencia_porcentaje = (row['diferencia'] / total_ventas) * 100
    ax.text(i, total_ventas / 2, f"{diferencia_porcentaje:.1f}%", ha='center', va='center', color='white')

# Configurar el gráfico
ax.set_xlabel('Categoría')
ax.set_ylabel('Ventas')
ax.set_title('Comparación de Ventas Reales y Predichas por Categoría')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x):,}'))
plt.show()

# Crear el gráfico de barras apiladas
fig, ax = plt.subplots(figsize=(10, 6))

# Barras para las ventas reales
ax.bar(merged_df_region['region'], merged_df_region['ventas_reales'], label='Ventas Reales')
# Barras para las ventas predichas (apiladas sobre las reales)
ax.bar(merged_df_region['region'], merged_df_region['ventas_predict'], bottom=merged_df_region['ventas_reales'], label='Ventas Predichas')

# Añadir etiquetas con el porcentaje de diferencia
for i, row in merged_df_region.iterrows():
    total_ventas = row['ventas_reales'] + row['ventas_predict']
    diferencia_porcentaje = (row['diferencia'] / total_ventas) * 100
    ax.text(i, total_ventas / 2, f"{diferencia_porcentaje:.1f}%", ha='center', va='center', color='white')

# Configurar el gráfico
ax.set_xlabel('Región')
ax.set_ylabel('Ventas')
ax.set_title('Comparación de Ventas Reales y Predichas por Región')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

# Crear el gráfico de barras apiladas
fig, ax = plt.subplots(figsize=(10, 6))

# Barras para las ventas reales
ax.bar(merged_df_store['store'], merged_df_store['ventas_reales'], label='Ventas Reales')

# Barras para las ventas predichas (apiladas sobre las reales)
ax.bar(merged_df_store['store'], merged_df_store['ventas_predict'], bottom=merged_df_store['ventas_reales'], label='Ventas Predichas')

# Añadir etiquetas con el porcentaje de diferencia
for i, row in merged_df_store.iterrows():
    total_ventas = row['ventas_reales'] + row['ventas_predict']
    diferencia_porcentaje = (row['diferencia'] / total_ventas) * 100
    ax.text(i, total_ventas / 2, f"{diferencia_porcentaje:.1f}%", ha='center', va='center', color='white')

# Configurar el gráfico
ax.set_xlabel('Tienda')
ax.set_ylabel('Ventas')
ax.set_title('Comparación de Ventas Reales y Predichas por Tienda')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

# Del dataset de prediciones mayo extraemos el total de ventas por region
total_ventas_por_region_mayo = df_4weeks.groupby('region')['ventas_predict'].sum()

# Datos para el gráfico
regions = ['New York', 'Philadelphia', 'Boston']
real_sales =  merged_df_region['ventas_reales'].tolist()
predicted_sales_april = merged_df_region['ventas_predict'].tolist()
predicted_sales_may = total_ventas_por_region_mayo.tolist()

# Crear el gráfico de barras
x = range(len(regions))
width = 0.25

fig, ax = plt.subplots(figsize=(10, 6))

rects1 = ax.bar(x, real_sales, width, color='blue', label='Ventas Reales Abril')
rects2 = ax.bar([i + width for i in x], predicted_sales_april, width, color='green', label='Predicciones Abril')
rects3 = ax.bar([i + width * 2 for i in x], predicted_sales_may, width, color='red', label='Predicciones Mayo')


# Configurar el gráfico
ax.set_ylabel('Ventas')
ax.set_title('Comparación de Ventas Reales y Predichas por Región')
ax.set_xticks([i + width for i in x])
ax.set_xticklabels(regions)
plt.legend()
plt.show()

